create database exercicio;

CREATE TABLE public.funcionarios (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	matricula int8 NULL,
	departamento varchar(255) NULL,
	cargo varchar(255) NULL,
	nome varchar(255) NULL,
	telefone int8 NULL,
	CONSTRAINT funcionarios_pkey PRIMARY KEY (id)
);


INSERT INTO public.funcionarios (matricula,departamento,cargo,nome,telefone) VALUES
	 (87120518,'UTI neo natal','médico','Ione lourdes Uberti',999752989),
	 (87110598,'Pronto Socorro','médico','Fancisco Narciso',988752875),
	 (98265147,'Pediatria','enfermeiro','Antonio Uberti',998753296),
	 (98253654,'UTI adulto','fisioterapeuta','Anita Garibaldi',34569825),
	 (9826546,'UTI adulto','medico','Bastiao cangaceiro',652345684);


CREATE TABLE public.pacientes (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NULL,
	data_nascimento timestamp NULL,
	telefone int8 NULL,
	internacao int4 NULL,
	CONSTRAINT pacientes_pkey PRIMARY KEY (id)
);


INSERT INTO public.pacientes (nome,data_nascimento,telefone,internacao) VALUES
	 ('francisco','2021-05-02 00:00:00',49998295441,1),
	 ('Maria da Graça','1985-05-12 00:00:00',34422451,3),
	 ('Breno Raimundo','1965-05-30 00:00:00',34423864,1),
	 ('Batata Frita','1987-08-28 00:00:00',34258715,5),
	 ('Batata Frita','1987-08-28 00:00:00',34258715,5),
	 ('Ione','1994-11-08 00:00:00',49998295441,2);


CREATE TABLE public.historico (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	id_medico int4 NULL,
	id_enfermeiro int4 NULL,
	entrada timestamp NULL,
	saida timestamp NULL,
	prontuario varchar(1000000) NULL,
	id_pacientes int4 NOT NULL,
	CONSTRAINT historico_pkey PRIMARY KEY (id)
);

ALTER TABLE public.historico
 ADD CONSTRAINT historico_id_pacientes_fkey FOREIGN KEY (id_pacientes)
  REFERENCES public.pacientes(id);

  INSERT INTO public.historico (id_medico,id_enfermeiro,entrada,saida,prontuario,id_pacientes) VALUES
	 (2,3,'2022-12-01 00:00:00','2022-12-15 00:00:00','Caganeira braba',4),
	 (2,3,'2022-12-01 00:00:00','2022-12-15 00:00:00','Noite de cachaçada',2);















SELECT pacientes AS id_paciente, COUNT(*) as internacao
FROM pacientes
JOIN historico
ON pacientes.id = historico.id_pacientes
GROUP BY pacientes
order by internacao desc ;


select * from paciente p
inner join historico h
on p.id = h.id_paciente
order by h.id_paciente desc